import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Check, Edit2, Layers, Plus, Trash2, X } from 'lucide-react-native';
import { fetchMobileCategories, fetchMobileEnvironments, saveMobileEnvironment, deleteMobileEnvironment, MobileCategory, MobileEnvironment } from '../services/mobileCategoryService';

interface Props { visible: boolean; dark: boolean; onClose: () => void; }

export const EnvironmentsManagerModal: React.FC<Props> = ({ visible, dark, onClose }) => {
  const [items, setItems] = useState<MobileEnvironment[]>([]);
  const [categories, setCategories] = useState<MobileCategory[]>([]);
  const [name, setName] = useState('');
  const [selected, setSelected] = useState<string[]>([]);
  const [editingId, setEditingId] = useState<string | undefined>();
  const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); try { const [envs, cats] = await Promise.all([fetchMobileEnvironments(), fetchMobileCategories()]); setItems(envs); setCategories(cats.filter(cat => cat.type !== 'environment')); } finally { setLoading(false); } };
  useEffect(() => { if (visible) void load(); }, [visible]);
  const reset = () => { setName(''); setSelected([]); setEditingId(undefined); };
  const save = async () => { if (!name.trim()) return; try { await saveMobileEnvironment(name, selected, editingId); reset(); await load(); } catch (error: any) { Alert.alert('Não foi possível salvar', error?.message || 'Tente novamente.'); } };
  const remove = (item: MobileEnvironment) => Alert.alert('Excluir ambiente', `Deseja excluir "${item.name}"?`, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await deleteMobileEnvironment(item.id); await load(); } catch (error: any) { Alert.alert('Exclusão bloqueada', error?.message || 'Desvincule as categorias antes de excluir.'); } } }]);
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={[styles.content, dark && styles.darkContent]}><View style={styles.header}><View style={styles.titleRow}><Layers size={20} color="#2563eb" /><Text style={[styles.title, dark && styles.light]}>Ambientes</Text></View><TouchableOpacity onPress={onClose}><X size={20} color={dark ? '#cbd5e1' : '#64748b'} /></TouchableOpacity></View><View style={styles.form}><TextInput value={name} onChangeText={setName} placeholder="Nome do ambiente..." placeholderTextColor="#94a3b8" style={[styles.input, dark && styles.darkInput, dark && styles.light]} /><TouchableOpacity onPress={() => void save()} style={styles.add}><Plus size={17} color="#fff" /></TouchableOpacity></View><Text style={[styles.label, dark && styles.light]}>Categorias vinculadas</Text><ScrollView style={styles.categoryList}>{categories.filter(c => c.type !== 'environment').map(category => <TouchableOpacity key={category.id} onPress={() => setSelected(prev => prev.includes(category.id) ? prev.filter(id => id !== category.id) : [...prev, category.id])} style={styles.categoryRow}><View style={[styles.checkbox, selected.includes(category.id) && styles.checked]}>{selected.includes(category.id) && <Check size={12} color="#fff" />}</View><Text style={[styles.categoryText, dark && styles.light]}>{category.name}</Text></TouchableOpacity>)}</ScrollView>{loading ? <ActivityIndicator color="#2563eb" /> : items.map(item => <View key={item.id} style={[styles.item, dark && styles.darkItem]}><View style={styles.flex}><Text style={[styles.itemName, dark && styles.light]}>{item.name}</Text><Text style={styles.itemMeta}>{item.categoryIds.length} categoria(s) vinculada(s)</Text></View><TouchableOpacity onPress={() => { setEditingId(item.id); setName(item.name); setSelected(item.categoryIds); }}><Edit2 size={15} color="#2563eb" /></TouchableOpacity><TouchableOpacity onPress={() => remove(item)}><Trash2 size={15} color="#ef4444" /></TouchableOpacity></View>)}</View></View></Modal>;
};

const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,.5)', justifyContent: 'flex-end' }, content: { maxHeight: '90%', backgroundColor: '#fff', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, gap: 12 }, darkContent: { backgroundColor: '#0f172a' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, title: { fontSize: 18, fontWeight: '900', color: '#0f172a' }, light: { color: '#f8fafc' }, form: { flexDirection: 'row', gap: 8 }, input: { flex: 1, height: 42, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, paddingHorizontal: 12 }, darkInput: { backgroundColor: '#1e293b', borderColor: '#334155' }, add: { width: 42, borderRadius: 12, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center' }, label: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', color: '#475569' }, categoryList: { maxHeight: 190 }, categoryRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8 }, checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 1, borderColor: '#cbd5e1' }, checked: { backgroundColor: '#2563eb', borderColor: '#2563eb', alignItems: 'center', justifyContent: 'center' }, categoryText: { color: '#334155', fontWeight: '700' }, item: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, borderRadius: 14, backgroundColor: '#f8fafc' }, darkItem: { backgroundColor: '#1e293b' }, flex: { flex: 1 }, itemName: { fontWeight: '800', color: '#0f172a' }, itemMeta: { fontSize: 11, color: '#64748b' } });
