import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Receipt, X } from 'lucide-react-native';
import { fetchLinkedProductOrders, LinkedProductOrder } from '../services/mobileProductOrderService';

interface Props { visible: boolean; dark: boolean; product: any | null; onClose: () => void; }
export const ProductLinkedOrdersModal: React.FC<Props> = ({ visible, dark, product, onClose }) => {
  const [orders, setOrders] = useState<LinkedProductOrder[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(false);
  useEffect(() => { if (!visible || !product?.id) return; let alive = true; setLoading(true); setError(false); fetchLinkedProductOrders(product.id).then(rows => { if (alive) setOrders(rows); }).catch(() => { if (alive) setError(true); }).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [visible, product?.id]);
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={[styles.content, dark && styles.darkContent]}><View style={styles.header}><View style={styles.titleRow}><Receipt size={20} color="#2563eb" /><View><Text style={[styles.title, dark && styles.light]}>Pedidos Vinculados</Text><Text style={styles.subtitle}>{product?.name || 'Produto'}</Text></View></View><TouchableOpacity onPress={onClose}><X size={20} color={dark ? '#cbd5e1' : '#64748b'} /></TouchableOpacity></View>{loading ? <ActivityIndicator color="#2563eb" style={styles.state} /> : error ? <Text style={styles.state}>Não foi possível carregar os pedidos.</Text> : orders.length === 0 ? <Text style={styles.state}>Nenhum pedido vinculado encontrado.</Text> : <ScrollView>{orders.map(order => <View key={order.id} style={[styles.row, dark && styles.darkRow]}><View style={styles.flex}><Text style={[styles.order, dark && styles.light]}>Pedido #{order.orderNumber}</Text><Text style={styles.meta}>{order.customer} · {order.date ? new Date(order.date).toLocaleDateString('pt-BR') : 'Data não informada'}</Text></View><Text style={styles.qty}>{order.quantity} un.</Text></View>)}</ScrollView>}</View></View></Modal>;
};
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,.5)', justifyContent: 'flex-end' }, content: { maxHeight: '80%', backgroundColor: '#fff', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, gap: 14 }, darkContent: { backgroundColor: '#0f172a' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, title: { fontSize: 18, fontWeight: '900', color: '#0f172a' }, subtitle: { color: '#64748b', fontSize: 11, marginTop: 2 }, light: { color: '#f8fafc' }, state: { textAlign: 'center', color: '#64748b', padding: 30 }, row: { flexDirection: 'row', alignItems: 'center', padding: 13, borderRadius: 14, backgroundColor: '#f8fafc', marginBottom: 8 }, darkRow: { backgroundColor: '#1e293b' }, flex: { flex: 1 }, order: { fontWeight: '800', color: '#0f172a', fontSize: 12 }, meta: { color: '#64748b', fontSize: 11, marginTop: 3 }, qty: { color: '#2563eb', fontWeight: '900' } });
