const fs = require('fs');
const file = 'erp/src/pages/App/Registrations/shared/modals/personForm/PersonIdentificationSection.tsx';
let c = fs.readFileSync(file, 'utf8');
const searchStr = 'placeholder="Tempo de entrega estimado"\r\n          />\r\n        </div>\r\n      )}';
const replacement = 'placeholder="Tempo de entrega estimado"\n          />\n        </div>\n      )}\n\n      {collectionName === \'suppliers\' && (\n        <div className="md:col-span-2 flex flex-col gap-2 mt-2">\n          <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 dark:text-slate-500">\n            Tipo de Móvel Fornecido\n          </label>\n          <div className="flex gap-4 items-center">\n            {[\n              { id: \'normal\', label: \'Normal\' },\n              { id: \'salvados\', label: \'Salvados\' },\n              { id: \'usados\', label: \'Usados\' },\n            ].map((option) => (\n              <label key={option.id} className="flex items-center gap-2 cursor-pointer">\n                <input\n                  type="checkbox"\n                  checked={formData.stockOrigins?.includes(option.id as any) || false}\n                  onChange={(e) => {\n                    const current = formData.stockOrigins || [];\n                    if (e.target.checked) {\n                      setFormData({ ...formData, stockOrigins: [...current, option.id as any] });\n                    } else {\n                      setFormData({\n                        ...formData,\n                        stockOrigins: current.filter((id) => id !== option.id),\n                      });\n                    }\n                  }}\n                  className="w-4 h-4 text-blue-600 rounded border-slate-300 focus:ring-blue-500"\n                />\n                <span className="text-sm font-bold text-slate-700 dark:text-slate-300">\n                  {option.label}\n                </span>\n              </label>\n            ))}\n          </div>\n        </div>\n      )}';

// Try with \r\n and \n
c = c.replace(/placeholder="Tempo de entrega estimado"\s*\/>\s*<\/div>\s*\)}/, replacement);
fs.writeFileSync(file, c);
