import { AdditionalCost, AdditionalCostItemAllocation } from './additionalCosts';

export interface InboundInvoiceItem {
    id?: string;
    itemNumber: number;
    productCode: string;
    productDescription: string;
    ean?: string;
    ncm: string;
    cest?: string;
    exTipi?: string;
    cfop: string;
    unit: string;
    quantity: number;
    unitCost: number;
    totalCost: number;
    tributaryUnit?: string;
    tributaryQuantity?: number;
    tributaryUnitCost?: number;
    freightValue?: number;
    insuranceValue?: number;
    otherExpensesValue?: number;
    ipiValue?: number;
    ipiPercent?: number;
    ipiCst?: string;
    discountValue?: number;
    icmsBaseValue?: number;
    icmsValue?: number;
    icmsPercent?: number;
    icmsStValue?: number;
    icmsStBaseValue?: number;
    icmsStPercent?: number;
    matchedProductId?: string;
    matchedVariationId?: string;
    productErpName?: string;
    linkedProductCode?: string;
    allocatedAdditionalCosts?: number;
    totalAdditionalCosts?: number;
    acquisitionCost?: number;
}

export type InboundInvoiceStatus = 'pending' | 'received' | 'manifested';

export interface InboundInvoice {
    id: string;
    nfeKey: string;
    nfeNumber: string;
    series: string;
    issuedAt: string;
    emitterCnpj: string;
    emitterName: string;
    emitterTradeName?: string;
    recipientCnpj: string;
    recipientName: string;
    totalProducts: number;
    totalFreight: number;
    totalIpi: number;
    ipiPercent?: number;
    totalDiscount?: number;
    totalInsurance?: number;
    totalOtherExpenses?: number;
    /** @deprecated legado; novos cadastros usam somente additionalCosts. */
    additionalFreight?: AdditionalCost;
    additionalCosts?: AdditionalCost[];
    additionalCostsTotal?: number;
    additionalCostAllocations?: AdditionalCostItemAllocation[];
    totalIcms?: number;
    totalIcmsSt?: number;
    freightPercent?: number;
    operationNature?: string;
    model?: string;
    protocol?: string;
    additionalInfo?: string;
    entryExitAt?: string;
    emitterIe?: string;
    emitterAddress?: Record<string, unknown>;
    supplierId?: string;
    originalDocumentPath?: string;
    originalDocumentMime?: string;
    extractionWarnings?: string[];
    extractionConfidence?: Record<string, unknown>;
    extractionStatus?: 'processing' | 'completed' | 'review_required' | 'failed';
    processedAt?: string;
    aiModel?: string;
    rawExtraction?: Record<string, unknown>;
    totalInvoice: number;
    status: InboundInvoiceStatus;
    itemsCount: number;
    receiptId?: string;
    receivedAt?: string;
    rawXml?: string;
    items: InboundInvoiceItem[];
    createdAt?: string;
}
