import { useRef, useState } from 'react';
import { toast } from 'react-toastify';
import { analyzeInboundInvoiceDocument, invoiceFromDocumentAnalysis } from '@/pages/utils/inboundNfe/inboundDocumentImportService';
import { saveInboundInvoice } from '@/pages/utils/inboundNfe/inboundInvoicesService';
import { InboundInvoice } from '@/pages/utils/inboundNfe/inboundNfeTypes';
import { fetchPersons } from '@/pages/utils/personService';
import Person from '@/pages/types/person.type';

type Props = { isOpen: boolean; onClose: () => void; onImportSuccess: (invoice: InboundInvoice) => void };
const accepted = 'application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg';

export function InboundDocumentImportModal({ isOpen, onClose, onImportSuccess }: Props) {
    const input = useRef<HTMLInputElement>(null);
    const [file, setFile] = useState<File | null>(null); const [invoice, setInvoice] = useState<InboundInvoice | null>(null); const [suppliers, setSuppliers] = useState<Person[]>([]); const [state, setState] = useState<'idle'|'uploading'|'analyzing'|'review'>('idle');
    if (!isOpen) return null;
    const select = (candidate?: File) => { if (!candidate) return; if (!['application/pdf','image/png','image/jpeg'].includes(candidate.type) || candidate.size > 12 * 1024 * 1024) return toast.error('Envie PDF, PNG ou JPG de até 12 MB.'); setFile(candidate); setInvoice(null); setState('idle'); };
    const analyze = async () => { if (!file) return; try { setState('uploading'); const result = await analyzeInboundInvoiceDocument(file); setState('analyzing'); const parsed = invoiceFromDocumentAnalysis(result); const list = await fetchPersons('suppliers'); setSuppliers(list); const taxId = parsed.emitterCnpj.replace(/\D/g, ''); const match = taxId ? list.find(s => (s.cpfCnpj || '').replace(/\D/g, '') === taxId) : undefined; setInvoice({ ...parsed, supplierId: match?.id }); setState('review'); } catch (e: any) { setState('idle'); toast.error(e.message || 'Falha ao analisar a NF.'); } };
    const save = async () => { if (!invoice) return; if (!invoice.nfeKey) return toast.error('A chave de acesso não foi identificada. Informe-a na revisão antes de salvar.'); try { const saved = await saveInboundInvoice(invoice); toast.success(`NF #${saved.nfeNumber || 'sem número'} pronta para recebimento.`); onImportSuccess(saved); onClose(); } catch (e: any) { toast.error(e.message || 'Não foi possível salvar a NF.'); } };
    return <div className="fixed inset-0 z-[1000002] flex items-center justify-center p-3 sm:p-6"><button className="absolute inset-0 bg-slate-950/60" aria-label="Fechar" onClick={onClose}/><section className="relative flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl dark:bg-slate-900"><header className="flex items-center justify-between border-b p-5 dark:border-slate-800"><div><h2 className="font-black text-slate-800 dark:text-white">Adicionar NF</h2><p className="text-xs text-slate-500">Envie o PDF ou uma foto da nota para extrair e revisar os dados.</p></div><button onClick={onClose} className="p-2 text-slate-400"><i className="bi bi-x-lg"/></button></header><div className="space-y-5 overflow-y-auto p-5">
        <input ref={input} type="file" accept={accepted} capture="environment" className="hidden" onChange={e => select(e.target.files?.[0])}/>
        {!invoice && <button type="button" onClick={() => input.current?.click()} className="flex w-full flex-col items-center rounded-2xl border-2 border-dashed border-indigo-200 p-8 text-indigo-700 hover:bg-indigo-50"><i className="bi bi-camera-fill text-3xl"/><span className="mt-2 text-xs font-black">Selecionar documento ou tirar foto</span><span className="mt-1 text-[10px] text-slate-500">PDF, PNG, JPG ou JPEG · até 12 MB</span></button>}
        {file && <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><div><p className="text-sm font-bold">{file.name}</p><p className="text-xs text-slate-500">{file.type || 'arquivo'} · {(file.size / 1024 / 1024).toFixed(1)} MB</p></div><button className="text-xs font-bold text-red-600" onClick={() => { setFile(null); setInvoice(null); setState('idle'); }}>Remover</button></div>}
        {state !== 'review' && file && <p className="text-xs text-indigo-700">{state === 'uploading' ? 'Enviando documento...' : state === 'analyzing' ? 'Analisando Nota Fiscal...' : 'Pronto para análise.'}</p>}
        {invoice && <div className="space-y-4"><div className="rounded-2xl border p-4 dark:border-slate-700"><h3 className="text-xs font-black uppercase text-slate-500">Revisão · NF</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['Chave de acesso','nfeKey'],['Número','nfeNumber'],['Série','series']].map(([label,key]) => <label key={key} className="text-[10px] font-bold uppercase text-slate-400">{label}<input value={(invoice as any)[key] || ''} onChange={e => setInvoice({...invoice,[key]:e.target.value})} className="mt-1 w-full border-b p-1 text-sm text-slate-800 dark:bg-slate-900 dark:text-white"/></label>)}</div><p className="mt-3 text-xs text-slate-600">Total: R$ {invoice.totalInvoice.toFixed(2)} · Frete: R$ {invoice.totalFreight.toFixed(2)} ({invoice.freightPercent || 0}%)</p></div><div className="rounded-2xl border p-4 dark:border-slate-700"><h3 className="text-xs font-black uppercase text-slate-500">Fornecedor extraído</h3><p className="mt-2 text-sm font-bold">{invoice.emitterName || 'Não identificado'}</p><p className="text-xs text-slate-500">{invoice.emitterCnpj || 'CNPJ/CPF não encontrado'}</p><label className="mt-3 block text-[10px] font-black uppercase text-slate-400">Fornecedor ERP <select value={invoice.supplierId || ''} onChange={e => setInvoice({...invoice, supplierId: e.target.value || undefined})} className="mt-1 w-full rounded-lg border p-2 text-sm normal-case text-slate-700"><option value="">Não vinculado — selecionar no recebimento</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.fullName} · {s.cpfCnpj || 'sem CNPJ/CPF'}</option>)}</select></label></div><div className="rounded-2xl border p-4 dark:border-slate-700"><h3 className="text-xs font-black uppercase text-slate-500">Itens ({invoice.items.length})</h3>{invoice.items.map(i => <p key={i.itemNumber} className="mt-2 text-xs"><b>{i.itemNumber}. {i.productDescription || 'Descrição não encontrada'}</b> · cód. fornecedor: {i.productCode || '—'} · {i.quantity} {i.unit} · R$ {i.totalCost.toFixed(2)}</p>)}</div>{invoice.extractionWarnings?.length ? <div className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Revise: {invoice.extractionWarnings.join(' · ')}</div> : null}</div>}
    </div><footer className="flex justify-end gap-3 border-t p-4 dark:border-slate-800"><button onClick={onClose} className="px-4 text-xs font-bold text-slate-500">Cancelar</button>{invoice ? <button onClick={() => void save()} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Salvar NF revisada</button> : <button disabled={!file || state !== 'idle'} onClick={() => void analyze()} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-black text-white disabled:opacity-50">Analisar NF</button>}</footer></section></div>;
}
