import { useRef, useState } from 'react';
import { toast } from 'react-toastify';
import ProductAutocomplete from '@/components/ProductAutocomplete';
import PersonFormModal from '@/pages/App/Registrations/shared/PersonFormModal';
import { analyzeInboundInvoiceDocument, invoiceFromDocumentAnalysis } from '@/pages/utils/inboundNfe/inboundDocumentImportService';
import { saveInboundInvoice } from '@/pages/utils/inboundNfe/inboundInvoicesService';
import { InboundInvoice, InboundInvoiceItem } from '@/pages/utils/inboundNfe/inboundNfeTypes';
import { fetchPersons } from '@/pages/utils/personService';
import { saveProductSupplierCode } from '@/pages/utils/productSupplierCodesService';
import Person from '@/pages/types/person.type';
import Product, { Variation } from '@/pages/types/product.type';

type Props = { isOpen: boolean; onClose: () => void; onImportSuccess: (invoice: InboundInvoice) => void };
const accepted = 'application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg';
const productName = (p: Product, v?: Variation) => v?.name || v?.title || p.name || p.title || p.description || '';

export function InboundDocumentImportModal({ isOpen, onClose, onImportSuccess }: Props) {
  const input = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null); const [invoice, setInvoice] = useState<InboundInvoice | null>(null);
  const [suppliers, setSuppliers] = useState<Person[]>([]); const [newSupplier, setNewSupplier] = useState(false); const [loading, setLoading] = useState(false);
  const setSupplier = (id: string) => setInvoice(current => current ? ({ ...current, supplierId: id || undefined, items: current.items.map(item => ({ ...item, matchedProductId: undefined, matchedVariationId: undefined })) }) : current);
  const setItem = (number: number, p: Product, v?: Variation) => setInvoice(current => current ? ({ ...current, items: current.items.map(item => item.itemNumber === number ? ({ ...item, matchedProductId: p.id, matchedVariationId: v?.id, productErpName: productName(p, v) } as InboundInvoiceItem) : item) }) : current);
  const analyze = async () => { if (!file) return; try { setLoading(true); const result = invoiceFromDocumentAnalysis(await analyzeInboundInvoiceDocument(file)); const list = await fetchPersons('suppliers'); const doc = result.emitterCnpj.replace(/\D/g, ''); const match = doc ? list.find(p => (p.cpfCnpj || '').replace(/\D/g, '') === doc) : undefined; setSuppliers(list); setInvoice({ ...result, supplierId: match?.id }); } catch (e: any) { toast.error(e.message || 'Falha ao analisar a NF.'); } finally { setLoading(false); } };
  const save = async () => { if (!invoice) return; if (String(invoice.model || '').replace(/\D/g, '') === '65') return toast.error('NFC-e não pode ser cadastrada como NF de Entrada.'); if (!invoice.supplierId) return toast.error('Selecione ou crie o fornecedor antes de salvar.'); if (!invoice.nfeKey) return toast.error('Informe a chave de acesso antes de salvar.'); try { await Promise.all(invoice.items.filter(i => i.matchedProductId && i.productCode).map(i => saveProductSupplierCode({ supplierId: invoice.supplierId!, productId: i.matchedProductId!, productVariationId: i.matchedVariationId, supplierProductCode: i.productCode, supplierDescription: i.productDescription }))); const saved = await saveInboundInvoice(invoice); toast.success('NF salva e pronta para recebimento.'); onImportSuccess(saved); onClose(); } catch (e: any) { toast.error(e.message || 'Não foi possível salvar a NF.'); } };
  if (!isOpen) return null;
  return <><div className="fixed inset-0 z-[1000002] flex items-center justify-center p-3"><button className="absolute inset-0 bg-slate-950/60" onClick={onClose}/><section className="relative flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-3xl bg-white dark:bg-slate-900"><header className="flex items-center justify-between border-b p-5"><div><h2 className="font-black">Adicionar NF</h2><p className="text-xs text-slate-500">Importe, selecione o fornecedor e vincule os produtos.</p></div><button onClick={onClose}><i className="bi bi-x-lg"/></button></header><main className="space-y-5 overflow-y-auto p-5"><input ref={input} type="file" accept={accepted} capture="environment" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f && ['application/pdf','image/png','image/jpeg'].includes(f.type) && f.size <= 12 * 1024 * 1024) { setFile(f); setInvoice(null); } else if (f) toast.error('Envie PDF, PNG ou JPG de até 12 MB.'); }}/>{!invoice && <button className="flex w-full flex-col items-center rounded-2xl border-2 border-dashed p-8 text-indigo-700" onClick={() => input.current?.click()}><i className="bi bi-camera-fill text-3xl"/><b className="mt-2 text-xs">Selecionar documento ou tirar foto</b></button>}{file && <div className="flex justify-between rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold">{file.name}</span><button className="text-xs text-red-600" onClick={() => { setFile(null); setInvoice(null); }}>Remover</button></div>}{file && !invoice && <button disabled={loading} onClick={() => void analyze()} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-black text-white">{loading ? 'Analisando Nota Fiscal...' : 'Analisar NF'}</button>}
  {invoice && <div className="space-y-4"><section className="rounded-2xl border p-4"><h3 className="text-xs font-black uppercase text-slate-500">Fornecedor</h3><p className="mt-2 font-bold">{invoice.emitterName || 'Emitente não identificado'}</p><p className="text-xs text-slate-500">{invoice.emitterCnpj || 'CNPJ/CPF não encontrado'}</p><div className="mt-3 flex gap-2"><select value={invoice.supplierId || ''} onChange={e => setSupplier(e.target.value)} className="min-w-0 flex-1 rounded-xl border p-2 text-sm"><option value="">Selecione o fornecedor</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.fullName} · {s.cpfCnpj || 'sem CNPJ/CPF'}</option>)}</select><button className="rounded-xl border border-emerald-200 px-3 text-xs font-black text-emerald-700" onClick={() => setNewSupplier(true)}>+ Novo fornecedor</button></div>{invoice.supplierId ? <p className="mt-2 text-xs font-bold text-emerald-700">Fornecedor vinculado. Os produtos estão liberados.</p> : <p className="mt-2 text-xs text-amber-700">Selecione o fornecedor para habilitar os produtos.</p>}</section>
  <section className="rounded-2xl border p-4"><h3 className="text-xs font-black uppercase text-slate-500">Itens da NF ({invoice.items.length})</h3>{invoice.items.map(item => <div key={item.itemNumber} className="grid gap-3 border-t py-4 first:border-t-0 sm:grid-cols-2"><div><b className="text-sm">{item.itemNumber}. {item.productDescription || 'Descrição não encontrada'}</b><p className="text-xs text-slate-500">Cód. fornecedor: {item.productCode || '—'} · {item.quantity} {item.unit}</p></div>{invoice.supplierId ? <ProductAutocomplete supplierId={invoice.supplierId} value={(item as any).productErpName || ''} isSelected={Boolean(item.matchedProductId)} placeholder="Vincular produto do ERP..." onSelect={(p, v) => setItem(item.itemNumber, p, v)}/> : <input disabled value="Selecione o fornecedor primeiro" className="rounded-xl border bg-slate-100 px-3 text-xs text-slate-400"/>}</div>)}</section>
  <button onClick={() => void save()} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Salvar NF revisada</button></div>}</main></section></div><PersonFormModal isOpen={newSupplier} onClose={() => setNewSupplier(false)} collectionName="suppliers" title="Novo Fornecedor" onSuccess={person => { setSuppliers(current => [...current, person]); setSupplier(person.id || ''); setNewSupplier(false); }}/></>;
}
