import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  containerDark: { backgroundColor: '#0f172a' },
  textDark: { color: '#f8fafc' },
  textMutedDark: { color: '#94a3b8' },
  cardContainer: { paddingHorizontal: 16, paddingTop: 10 },
  pageHeaderWrapper: { backgroundColor: '#f8fafc', borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  pageHeaderWrapperDark: { backgroundColor: '#0f172a', borderBottomColor: '#1e293b' },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  periodBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingLeft: 12,
    paddingRight: 8,
    height: 38,
    gap: 8,
    flex: 1,
  },
  periodBtnDark: { backgroundColor: '#1e293b', borderColor: '#334155' },
  periodBtnLeft: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  periodLabel: { fontSize: 12, fontWeight: '700', color: '#64748b' },
  periodValueWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    flex: 1,
    justifyContent: 'flex-end',
  },
  periodValueWrapperDark: { backgroundColor: '#0f172a' },
  periodValue: { fontSize: 12, fontWeight: '800', color: '#0f172a' },
  filtersContainer: { paddingHorizontal: 16, paddingBottom: 14, gap: 10 },
  paginationContainer: { paddingVertical: 20, alignItems: 'center', justifyContent: 'center' },
  paginationContainerDark: { backgroundColor: '#0f172a' },
  paginationRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  pageBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pageBtnDark: { backgroundColor: '#1e293b', borderColor: '#334155' },
  pageBtnDisabled: { opacity: 0.4, backgroundColor: '#f1f5f9' },
  pageText: { fontSize: 13, fontWeight: '700', color: '#334155' },
  emptyState: {
    margin: 16,
    padding: 24,
    borderRadius: 16,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  emptyStateDark: { backgroundColor: 'rgba(124,45,18,0.2)', borderColor: '#9a3412' },
  errorTitle: { color: '#c2410c', fontSize: 14, fontWeight: '800', textAlign: 'center' },
  errorMessage: { color: '#9a3412', fontSize: 12, marginTop: 6, textAlign: 'center' },
  emptyTitle: { color: '#334155', fontSize: 14, fontWeight: '800', textAlign: 'center' },
  emptyMessage: { color: '#64748b', fontSize: 12, marginTop: 6, textAlign: 'center' },
});
