import React, { useEffect, useRef, useState } from 'react';
import { PostCampaign } from '../types/postCreator';

type Props = { campaigns: PostCampaign[]; onClose: () => void; onSave: (value: Partial<PostCampaign>) => Promise<void>; onRemove: (id: string) => Promise<void>; onSavingChange: (saving: boolean) => void };

export function CampaignManagerModal({ campaigns, onClose, onSave, onRemove, onSavingChange }: Props) {
  const [editing, setEditing] = useState<Partial<PostCampaign>>(); const [busy, setBusy] = useState(false); const initialEdit = useRef(true);
  const persist = async (closeAfterSave = false) => { if (!editing?.name?.trim()) return; setBusy(true); onSavingChange(true); try { await onSave(editing); if (closeAfterSave) setEditing(undefined); } finally { setBusy(false); onSavingChange(false); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); await persist(true); };
  useEffect(() => {
    if (!editing?.id) { initialEdit.current = true; return; }
    if (initialEdit.current) { initialEdit.current = false; return; }
    const timeout = window.setTimeout(() => void persist(), 700);
    return () => window.clearTimeout(timeout);
  }, [editing]);
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-xl border border-slate-700 bg-slate-900 text-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-700 p-5"><div><h2 className="font-bold">Gerenciar Campanhas</h2><p className="mt-1 text-xs text-slate-400">Crie, edite, desative ou exclua campanhas.</p></div><button onClick={onClose}>✕</button></header><div className="max-h-[65vh] overflow-auto p-5">{editing ? <form onSubmit={event => void save(event)} className="space-y-3"><label className="block text-xs">Nome<input required value={editing.name || ''} onChange={event => setEditing(value => ({ ...value, name: event.target.value }))} className="mt-1 w-full rounded bg-slate-950 p-2" /></label><label className="block text-xs">Descrição<textarea value={editing.description || ''} onChange={event => setEditing(value => ({ ...value, description: event.target.value }))} className="mt-1 w-full rounded bg-slate-950 p-2" rows={3} /></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={editing.active !== false} onChange={event => setEditing(value => ({ ...value, active: event.target.checked }))} /> Campanha ativa</label><div className="flex justify-end gap-2"><button type="button" onClick={() => setEditing(undefined)} className="px-3 py-2 text-xs">Cancelar</button><button disabled={busy} className="rounded bg-indigo-600 px-3 py-2 text-xs font-bold">{editing.id ? 'Salvar agora' : 'Criar campanha'}</button></div></form> : <><button onClick={() => setEditing({ name: '', active: true })} className="mb-3 rounded border border-indigo-400 px-3 py-2 text-xs text-indigo-300">+ Criar campanha</button><div className="space-y-2">{campaigns.map(campaign => <article key={campaign.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-700 p-3"><div><b className="text-sm">{campaign.name}</b><p className="text-xs text-slate-400">{campaign.active ? 'Ativa' : 'Desativada'}{campaign.description ? ` · ${campaign.description}` : ''}</p></div><div className="flex gap-2 text-xs"><button onClick={() => setEditing(campaign)} className="text-indigo-300">Editar</button><button onClick={() => { if (window.confirm(`Excluir a campanha "${campaign.name}"?`)) void onRemove(campaign.id); }} className="text-rose-300">Excluir</button></div></article>)}</div></>}</div></div></div>;
}
