import React from 'react';
import { ElementModel, PostFormat } from '../types/postCreator';

type Props = { format: PostFormat; product: { name: string; price: string; oldPrice?: string; installment?: string; primary?: string } | null; models: ElementModel[]; imageUrl?: string; stale: boolean };
export function PostCreatorPreview({ format, product, models, imageUrl, stale }: Props) {
  const model = (type: string) => models.find(item => item.elementType === type);
  if (!product) return <div className="flex aspect-[4/5] w-full max-w-md items-center justify-center rounded-xl border border-dashed border-slate-700 text-sm text-slate-500">Selecione um produto para preview.</div>;
  return <div className="relative w-full max-w-[480px] overflow-hidden rounded-xl bg-[#21130e] shadow-2xl" style={{ aspectRatio: format === '4:5' ? '4 / 5' : '9 / 16' }}>{imageUrl ? <img src={imageUrl} alt="Preview composto" className="absolute inset-0 h-full w-full object-cover" /> : <><div className="absolute inset-0 bg-gradient-to-br from-red-950 via-[#24170e] to-amber-900/70" />{product.primary && <img src={product.primary} alt={product.name} className="absolute bottom-[14%] left-[5%] h-[60%] w-[61%] object-contain" />}</>}<div className="absolute left-[6%] top-[6%] max-w-[60%] text-xl font-black uppercase leading-none text-white drop-shadow">{model('TITLE') ? 'Oferta especial' : product.name}</div>{model('BADGE')?.generatedAssetUrl && <img src={model('BADGE')!.generatedAssetUrl!} alt="Selo" className="absolute right-[5%] top-[5%] h-[17%] w-[25%] object-contain" />}<div className="absolute bottom-[8%] right-[5%] rounded-lg bg-red-600 px-3 py-2 text-right font-black text-white shadow-lg">{product.oldPrice && <div className="text-[10px] line-through opacity-80">{product.oldPrice}</div>}<div className="text-xl">{product.price}</div><div className="text-[10px]">{product.installment || 'Em até 10x sem juros'}</div></div>{stale && <span className="absolute bottom-2 left-2 rounded bg-amber-400 px-2 py-1 text-[10px] font-bold text-slate-950">Configuração alterada</span>}</div>;
}
