-- ==========================================
-- 🛠️ CORREÇÃO DE ESQUEMA: PRODUTOS (MATERIAL, CORES & DETALHES)
-- Adiciona colunas faltantes que estavam impedindo o salvamento de dados.
-- ==========================================

DO $$ 
BEGIN 
    -- 1. Detalhes Técnicos
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='material') THEN 
        ALTER TABLE public.products ADD COLUMN material TEXT; 
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='colors') THEN 
        ALTER TABLE public.products ADD COLUMN colors TEXT; 
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='main_differential') THEN 
        ALTER TABLE public.products ADD COLUMN main_differential TEXT; 
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='not_included') THEN 
        ALTER TABLE public.products ADD COLUMN not_included TEXT; 
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='supplier_ref') THEN 
        ALTER TABLE public.products ADD COLUMN supplier_ref TEXT; 
    END IF;

     IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='no_colors') THEN 
        ALTER TABLE public.products ADD COLUMN no_colors BOOLEAN DEFAULT FALSE; 
    END IF;

    -- 2. Tabela de Materiais (Lookup) para o CRUD solicitado
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='product_materials') THEN
        CREATE TABLE public.product_materials (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );

        -- Inserindo valores iniciais padrão
        INSERT INTO public.product_materials (name) VALUES 
        ('MDP'), ('MDF'), ('MDP/MDF'), ('MAD. MACIÇA'), ('METAL/MDP'), ('METAL')
        ON CONFLICT DO NOTHING;
    END IF;

END $$;
