export const PRODUCT_ENVIRONMENT_OPTIONS = [
    'SALA DE JANTAR', 'SALA DE ESTAR', 'COZINHA', 'QUARTO', 'LAVANDERIA', 'BANHEIRO',
    'LAVANDEIRA', 'ESCRITORIO', 'ESCRITÓRIO', 'VARANDA', 'ÁREA GOURMET', 'GARAGEM',
];
