import type { Product } from '../../types/product.type';

export const INITIAL_PRODUCT_FORM_DATA: Partial<Product> = {
    description: '',
    code: '',
    unit: 'UN',
    unitPrice: 0,
    costPrice: 0,
    finalPurchasePrice: 0,
    ipiPercent: 0,
    ipiType: 'percentage',
    freightCost: 0,
    freightType: 'fixed',
    stock: 0,
    minStock: 0,
    hasVariations: true,
    variations: [],
    images: [],
    marketplaceTitle: '',
    condition: 'novo',
    itemType: 'product',
    active: false,
    status: 'draft',
    isDraft: true,
    isCombo: false,
    comboItems: [],
    categoryIds: [],
    fiscal: { ncm: '', cest: '', ncmDescription: '', cfop: '5102', icmsPercent: 0 },
    launchInitialStock: false,
    line: '',
    brand: '',
    colors: '',
    material: '',
    supplierRef: '',
    observations: '',
    noColors: false,
    environment: '',
    hasNoLine: false,
    noBrand: false,
};
