import React from 'react';
import type { InventoryAuditSession } from './InventoryAudit';

interface Props { session: InventoryAuditSession | null; onClose: () => void; }

const InventoryAuditDetailsModal: React.FC<Props> = ({ session, onClose }) => {
    if (!session) return null;
    return <div className="fixed inset-0 z-[999999] flex items-center justify-center bg-slate-950/60 p-4" onClick={onClose}><section className="max-h-[90vh] w-full max-w-4xl overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-slate-900" onClick={(event) => event.stopPropagation()}><header className="flex items-center justify-between border-b border-slate-100 px-6 py-4 dark:border-slate-800"><div><h2 className="text-sm font-black uppercase tracking-wider text-slate-800 dark:text-white">Detalhes do inventário</h2><p className="mt-1 text-xs font-bold text-slate-400">{new Date(session.date).toLocaleString('pt-BR')}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><i className="bi bi-x-lg" /></button></header><div className="grid grid-cols-2 gap-3 border-b border-slate-100 p-5 text-center dark:border-slate-800 sm:grid-cols-3"><div><span className="block text-[10px] font-black uppercase tracking-widest text-slate-400">Itens contados</span><strong className="text-lg text-slate-700 dark:text-slate-100">{session.productsCount}</strong></div><div><span className="block text-[10px] font-black uppercase tracking-widest text-slate-400">Ajustes gerados</span><strong className="text-lg text-emerald-600">{session.adjustmentsCount}</strong></div><div><span className="block text-[10px] font-black uppercase tracking-widest text-slate-400">Diferenças</span><strong className="text-lg text-slate-700 dark:text-slate-100">{session.items.filter(item => item.physicalCount !== item.systemStock).length}</strong></div></div><div className="max-h-[55vh] overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-[10px] font-black uppercase tracking-widest text-slate-400 dark:bg-slate-950"><tr><th className="px-5 py-3">Produto / variação</th><th className="px-5 py-3 text-center">Saldo no momento</th><th className="px-5 py-3 text-center">Contagem física</th><th className="px-5 py-3 text-center">Ajuste</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{session.items.map((item, index) => { const adjustment = item.physicalCount - item.systemStock; return <tr key={`${item.productId}-${item.variationId || index}`}><td className="px-5 py-4 font-bold text-slate-700 dark:text-slate-200">{item.name}</td><td className="px-5 py-4 text-center">{item.systemStock}</td><td className="px-5 py-4 text-center font-black">{item.physicalCount}</td><td className={`px-5 py-4 text-center font-black ${adjustment > 0 ? 'text-emerald-600' : adjustment < 0 ? 'text-rose-600' : 'text-slate-400'}`}>{adjustment > 0 ? `+${adjustment}` : adjustment}</td></tr>; })}</tbody></table></div></section></div>;
};

export default InventoryAuditDetailsModal;
