import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Calendar, Clock, DollarSign, FileText, Hammer, MapPin, Navigation, Package, Truck, User, Wrench } from 'lucide-react-native';
import { formatFullAddress, formatItemNameExact, formatOrderDate } from '../../utils/orderUtils';

export function OrderTypeBadges({ assistance, pickup, internal, outside }: any) {
  return <View style={styles.badges}><View style={[styles.badge, assistance ? styles.orange : pickup ? styles.purple : styles.green]}>{assistance ? <Wrench size={14} color="#fff" /> : pickup ? <Package size={14} color="#fff" /> : <Truck size={14} color="#fff" />}<Text style={styles.badgeText}>{assistance ? 'ASSISTÊNCIA' : pickup ? 'RETIRADA' : 'ENTREGA'}</Text></View>{internal && <View style={[styles.badge, styles.orange]}><Hammer size={14} color="#fff" /><Text style={styles.badgeText}>MONTAGEM DEPÓSITO</Text></View>}{outside && <View style={[styles.badge, styles.red]}><Hammer size={14} color="#fff" /><Text style={styles.badgeText}>MONTAGEM FORA</Text></View>}</View>;
}

const Header = ({ icon, title, dark }: any) => <View style={styles.header}>{icon}<Text style={[styles.title, dark && styles.light]}>{title}</Text></View>;
const Card = ({ children, dark }: any) => <View style={[styles.card, dark && styles.cardDark]}>{children}</View>;

export function CustomerSection({ customer, dark }: any) {
  const contacts = (customer.additionalContacts || []).filter((contact: any) => contact?.name || contact?.phone);
  return <Card dark={dark}><Header dark={dark} icon={<User size={18} color="#2563eb" />} title="DADOS DO CLIENTE" /><Text style={[styles.strong, dark && styles.light]}>{customer.fullName || customer.name || 'Cliente Consumidor'}</Text>{customer.phone && <Text style={styles.detail}>📞 Telefone principal: {customer.phone}</Text>}{contacts.map((contact: any, index: number) => <View key={index} style={[styles.contact, dark && styles.contactDark]}><Text style={styles.contactName}>{contact.name || 'Contato adicional'}</Text><Text style={[styles.contactPhone, dark && styles.light]}>📞 {contact.phone || 'Telefone não informado'}</Text></View>)}{customer.document && <Text style={styles.detail}>📄 CPF / CNPJ: {customer.document}</Text>}</Card>;
}

export function AddressSection({ shipping, customer, schedule, order, dark }: any) {
  const distance = shipping.distance != null ? Number(shipping.distance).toFixed(1) : null;
  const duration = shipping.durationMinutes != null ? Math.round(Number(shipping.durationMinutes)) : null;
  return <Card dark={dark}><Header dark={dark} icon={<MapPin size={18} color="#ef4444" />} title="ENDEREÇO E AGENDAMENTO" /><Text style={[styles.addressText, dark && styles.light]}>{formatFullAddress(shipping, customer)}</Text>{(distance || duration) && <View style={styles.route}>{distance && <View style={styles.inline}><Navigation size={14} color="#2563eb" /><Text style={styles.routeText}>Distância: {distance} KM</Text></View>}{duration && <Text style={styles.detail}>Tempo estimado: ~ {duration} MIN</Text>}</View>}<View style={styles.schedule}><View style={styles.inline}><Calendar size={14} color="#64748b" /><Text style={styles.detail}>Data: {formatOrderDate(schedule.date || order.created_at)}</Text></View><View style={styles.inline}><Clock size={14} color="#64748b" /><Text style={styles.detail}>Horário: {schedule.startTime ? `${schedule.startTime}${schedule.endTime ? ` - ${schedule.endTime}` : ''}` : 'Não definido'}</Text></View></View></Card>;
}

export function ItemsSection({ items, total, pendingTotal, dark }: any) {
  return <><Card dark={dark}><Header dark={dark} icon={<FileText size={18} color="#7c3aed" />} title={`ITENS DO PEDIDO (${items.length})`} />{items.map((item: any, index: number) => { const qty = Number(item.quantity || item.qty || 1); const price = Number(item.total || item.price || item.unitPrice || 0); return <View key={index} style={styles.item}><Text style={[styles.itemName, dark && styles.light]}><Text style={styles.qty}>{qty}x</Text> {formatItemNameExact(item)}</Text>{price > 0 && <Text style={styles.price}>R$ {price.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</Text>}</View>; })}</Card><View style={[styles.totalCard, dark && styles.totalDark]}>{pendingTotal > 0 && <View style={styles.pendingBox}><Text style={styles.pendingLabel}>VALOR A PAGAR</Text><Text style={styles.pendingValue}>R$ {pendingTotal.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</Text></View>}<View style={styles.totalRow}><View style={styles.inline}><DollarSign size={21} color="#16a34a" /><Text style={[styles.totalTitle, dark && styles.light]}>VALOR TOTAL</Text></View><Text style={styles.total}>R$ {total.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</Text></View></View></>;
}

const styles = StyleSheet.create({
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, badge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 }, green: { backgroundColor: '#10b981' }, purple: { backgroundColor: '#a855f7' }, orange: { backgroundColor: '#f59e0b' }, red: { backgroundColor: '#ef4444' }, badgeText: { fontSize: 10, fontWeight: '900', color: '#fff' }, card: { backgroundColor: '#fff', padding: 16, borderRadius: 20, borderWidth: 1, borderColor: '#e2e8f0', gap: 10 }, cardDark: { backgroundColor: '#1e293b', borderColor: '#334155' }, header: { flexDirection: 'row', alignItems: 'center', gap: 8 }, title: { fontSize: 12, fontWeight: '900', color: '#0f172a' }, light: { color: '#f8fafc' }, strong: { fontSize: 16, fontWeight: '900', color: '#0f172a' }, detail: { fontSize: 12, fontWeight: '700', color: '#64748b' }, contact: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 11, padding: 10, gap: 3 }, contactDark: { backgroundColor: '#0f172a', borderColor: '#334155' }, contactName: { fontSize: 10, fontWeight: '900', color: '#2563eb', textTransform: 'uppercase' }, contactPhone: { fontSize: 13, fontWeight: '800', color: '#334155' }, addressText: { fontSize: 13, fontWeight: '700', color: '#334155', lineHeight: 19 }, route: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, backgroundColor: '#eff6ff', padding: 9, borderRadius: 11 }, routeText: { fontSize: 12, fontWeight: '800', color: '#2563eb' }, inline: { flexDirection: 'row', alignItems: 'center', gap: 5 }, schedule: { gap: 7 }, item: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' }, itemName: { flex: 1, fontSize: 13, fontWeight: '700', color: '#1e3a8a' }, qty: { color: '#7c3aed', fontWeight: '900' }, price: { fontSize: 12, fontWeight: '800', color: '#16a34a' }, totalCard: { backgroundColor: '#f0fdf4', padding: 17, borderRadius: 20, borderWidth: 1, borderColor: '#bbf7d0', gap: 10 }, totalDark: { backgroundColor: '#064e3b', borderColor: '#047857' }, pendingBox: { borderBottomWidth: 1, borderBottomColor: '#bfdbfe', paddingBottom: 9 }, pendingLabel: { fontSize: 10, fontWeight: '900', color: '#2563eb' }, pendingValue: { fontSize: 18, fontWeight: '900', color: '#2563eb' }, totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, totalTitle: { fontSize: 12, fontWeight: '900', color: '#065f46' }, total: { fontSize: 17, fontWeight: '900', color: '#16a34a' },
});
