-- migration: create_services_table.sql

CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_draft BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_services_is_draft ON public.services(is_draft);

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated and anon to read services" ON public.services;
CREATE POLICY "Allow authenticated and anon to read services"
ON public.services FOR SELECT
TO authenticated, anon
USING (true);

DROP POLICY IF EXISTS "Allow authenticated and anon to insert services" ON public.services;
CREATE POLICY "Allow authenticated and anon to insert services"
ON public.services FOR INSERT
TO authenticated, anon
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated and anon to update services" ON public.services;
CREATE POLICY "Allow authenticated and anon to update services"
ON public.services FOR UPDATE
TO authenticated, anon
USING (true);

DROP POLICY IF EXISTS "Allow authenticated and anon to delete services" ON public.services;
CREATE POLICY "Allow authenticated and anon to delete services"
ON public.services FOR DELETE
TO authenticated, anon
USING (true);
