import { GridModel } from './LabelGridModelModal';
import { formatCurrency } from '../../../utils/formatters';
import { LabelItemConfig } from './LabelGrid';

export const calculateLabelDimensions = (m: any) => {
    const paperW = m.paperSize === 'A4' ? 210 : m.paperSize === 'A3' ? 297 : m.paperSize === 'A5' ? 148 : m.paperWidth || 210;
    const paperH = m.paperSize === 'A4' ? 297 : m.paperSize === 'A3' ? 420 : m.paperSize === 'A5' ? 210 : m.paperHeight || 297;
    
    const usableW = paperW - (m.marginL || 0) - (m.marginR || 0) - ((m.columns - 1) * (m.gapH || 0));
    const usableH = paperH - (m.marginT || 0) - (m.marginB || 0) - ((m.rows - 1) * (m.gapV || 0));
    
    return {
        width: (usableW / m.columns).toFixed(1),
        height: (usableH / m.rows).toFixed(1)
    };
};

export const processProductData = (data: any[]) => {
    const flattened: any[] = [];
    data.forEach((product: any) => {
        flattened.push({ ...product, isParent: product.hasVariations });
        if (product.hasVariations && product.variations) {
            product.variations.forEach((v: any) => {
                flattened.push({
                    ...product,
                    id: `${product.id}_${v.sku}`,
                    sku: v.sku,
                    description: v.syncDescription ? `${product.description} - ${v.name}` : v.name,
                    variationName: v.name,
                    unitPrice: v.unitPrice,
                    costPrice: v.costPrice,
                    stock: v.stock,
                    active: v.active,
                    images: v.images || [],
                    parentImages: product.images || [],
                    isVariation: true,
                    parentId: product.id,
                    categoryIds: product.categoryIds,
                    category: product.category,
                    unit: product.unit
                });
            });
        }
    });
    return flattened;
};

export const mapModelToDb = (model: GridModel) => ({
    name: model.name,
    category: model.category,
    columns: Math.round(model.columns || 1),
    rows: Math.round(model.rows || 1),
    margin_t: Number(model.marginT ?? 10),
    margin_b: Number(model.marginB ?? 10),
    margin_l: Number(model.marginL ?? 10),
    margin_r: Number(model.marginR ?? 10),
    gap_h: Number(model.gapH ?? 2),
    gap_v: Number(model.gapV ?? 2),
    paper_size: model.paperSize,
    paper_width: Number(model.paperWidth ?? 210),
    paper_height: Number(model.paperHeight ?? 297),
    icon: model.icon,
    type: model.type || 'rect',
    name_font_size: Math.round(model.nameFontSize || 7),
    name_color: model.nameColor || '#1e293b',
    price_font_size: Math.round(model.priceFontSize || 11),
    price_color: model.priceColor || '#1e293b',
    promo_font_size: Math.round(model.promoFontSize || 9),
    promo_color: model.promoColor || '#16a34a',
    name_pos_x: Math.round(model.namePosX ?? 50),
    name_pos_y: Math.round(model.namePosY ?? 30),
    price_pos_x: Math.round(model.pricePosX ?? 50),
    price_pos_y: Math.round(model.pricePosY ?? 60),
    promo_pos_x: Math.round(model.promoPosX ?? 50),
    promo_pos_y: Math.round(model.promoPosY ?? 75),
    barcode_pos_x: Math.round(model.barcodePosX ?? 50),
    barcode_pos_y: Math.round(model.barcodePosY ?? 90),
    price_font_size_tens: (model.priceFontSizeTens !== undefined && model.priceFontSizeTens !== null) ? Math.round(model.priceFontSizeTens) : null,
    price_font_size_hundreds: (model.priceFontSizeHundreds !== undefined && model.priceFontSizeHundreds !== null) ? Math.round(model.priceFontSizeHundreds) : null,
    price_font_size_thousands: (model.priceFontSizeThousands !== undefined && model.priceFontSizeThousands !== null) ? Math.round(model.priceFontSizeThousands) : null,
    price_font_size_ten_thousands: (model.priceFontSizeTenThousands !== undefined && model.priceFontSizeTenThousands !== null) ? Math.round(model.priceFontSizeTenThousands) : null,
    promo_price_color: model.promoPriceColor,
    old_price_color: model.oldPriceColor,
    promo_price_font_size: Math.round(model.promoPriceFontSize || 24),
    name_width: Math.round(model.nameWidth ?? 80),
    name_height: Math.round(model.nameHeight ?? 20),
    price_width: Math.round(model.priceWidth ?? 80),
    price_height: Math.round(model.priceHeight ?? 30),
    promo_width: Math.round(model.promoWidth ?? 80),
    promo_height: Math.round(model.promoHeight ?? 40),
    name_bold: model.nameBold,
    name_align: model.nameAlign,
    name_valign: model.nameVAlign,
    price_bold: model.priceBold,
    price_align: model.priceAlign,
    price_valign: model.priceVAlign,
    promo_bold: model.promoBold,
    promo_align: model.promoAlign,
    promo_valign: model.promoVAlign,
    promo_price_bold: model.promoPriceBold,
    promo_price_align: model.promoPriceAlign,
    promo_price_valign: model.promoPriceVAlign,
    old_price_bold: (model.oldPriceBold !== undefined) ? model.oldPriceBold : null,
    old_price_font_size: (model.oldPriceFontSize !== undefined && model.oldPriceFontSize !== null) ? Math.round(model.oldPriceFontSize) : null,
    old_price_align: model.oldPriceAlign,
    old_price_valign: model.oldPriceVAlign,
    bg_color: model.bg_color,
    name_bg_color: model.nameBgColor,
    price_bg_color: model.priceBgColor,
    promo_bg_color: model.promoBgColor,
    price_format: model.priceFormat,
    price_symbol_font_size: model.priceSymbolFontSize ?? null,
    price_decimals_font_size: model.priceDecimalsFontSize ?? null,
    price_symbol_pos_x: (model.priceSymbolPosX !== undefined && model.priceSymbolPosX !== null) ? Math.round(model.priceSymbolPosX) : null,
    price_symbol_pos_y: (model.priceSymbolPosY !== undefined && model.priceSymbolPosY !== null) ? Math.round(model.priceSymbolPosY) : null,
    price_decimals_pos_x: (model.priceDecimalsPosX !== undefined && model.priceDecimalsPosX !== null) ? Math.round(model.priceDecimalsPosX) : null,
    price_decimals_pos_y: (model.priceDecimalsPosY !== undefined && model.priceDecimalsPosY !== null) ? Math.round(model.priceDecimalsPosY) : null,
    price_symbol_color: model.priceSymbolColor,
    price_decimals_color: model.priceDecimalsColor,
    price_symbol_bold: model.priceSymbolBold,
    price_decimals_bold: model.priceDecimalsBold,
    old_price_pos_x: (model.oldPricePosX !== undefined && model.oldPricePosX !== null) ? Math.round(model.oldPricePosX) : null, 
    old_price_pos_y: (model.oldPricePosY !== undefined && model.oldPricePosY !== null) ? Math.round(model.oldPricePosY) : null,
    old_price_width: (model.oldPriceWidth !== undefined && model.oldPriceWidth !== null) ? Math.round(model.oldPriceWidth) : null,
    old_price_height: (model.oldPriceHeight !== undefined && model.oldPriceHeight !== null) ? Math.round(model.oldPriceHeight) : null,
    promo_name_pos_x: (model.promoNamePosX !== undefined && model.promoNamePosX !== null) ? Math.round(model.promoNamePosX) : null,
    promo_name_pos_y: (model.promoNamePosY !== undefined && model.promoNamePosY !== null) ? Math.round(model.promoNamePosY) : null,
    promo_name_font_size: (model.promoNameFontSize !== undefined && model.promoNameFontSize !== null) ? Math.round(model.promoNameFontSize) : null,
    promo_name_align: model.promoNameAlign,
    promo_name_valign: model.promoNameVAlign,
    promo_name_color: model.promoNameColor,
    promo_name_bold: model.promoNameBold,
    promo_name_width: (model.promoNameWidth !== undefined && model.promoNameWidth !== null) ? Math.round(model.promoNameWidth) : null,
    promo_name_height: (model.promoNameHeight !== undefined && model.promoNameHeight !== null) ? Math.round(model.promoNameHeight) : null,
    promo_name_bg_color: model.promoNameBgColor,
    promo_barcode_pos_x: (model.promoBarcodePosX !== undefined && model.promoBarcodePosX !== null) ? Math.round(model.promoBarcodePosX) : null,
    promo_barcode_pos_y: (model.promoBarcodePosY !== undefined && model.promoBarcodePosY !== null) ? Math.round(model.promoBarcodePosY) : null,
    promo_price_symbol_pos_x: (model.promoPriceSymbolPosX !== undefined && model.promoPriceSymbolPosX !== null) ? Math.round(model.promoPriceSymbolPosX) : null,
    promo_price_symbol_pos_y: (model.promoPriceSymbolPosY !== undefined && model.promoPriceSymbolPosY !== null) ? Math.round(model.promoPriceSymbolPosY) : null,
    promo_price_symbol_font_size: (model.promoPriceSymbolFontSize !== undefined && model.promoPriceSymbolFontSize !== null) ? Math.round(model.promoPriceSymbolFontSize) : null,
    promo_price_symbol_color: model.promoPriceSymbolColor,
    promo_price_symbol_bold: model.promoPriceSymbolBold,
    promo_price_decimals_pos_x: (model.promoPriceDecimalsPosX !== undefined && model.promoPriceDecimalsPosX !== null) ? Math.round(model.promoPriceDecimalsPosX) : null,
    promo_price_decimals_pos_y: (model.promoPriceDecimalsPosY !== undefined && model.promoPriceDecimalsPosY !== null) ? Math.round(model.promoPriceDecimalsPosY) : null,
    promo_price_decimals_font_size: (model.promoPriceDecimalsFontSize !== undefined && model.promoPriceDecimalsFontSize !== null) ? Math.round(model.promoPriceDecimalsFontSize) : null,
    promo_price_decimals_color: model.promoPriceDecimalsColor,
    promo_price_decimals_bold: model.promoPriceDecimalsBold,
    font_family: model.fontFamily,
    extra_fields: model.extraFields || [],
    extra_fields_promo: model.extraFieldsPromo || [],
    image_fit: model.imageFit || 'contain',
    safety_margin: model.imageScale || 1,
    preview_image: model.previewImage || null,
    base_model_id: model.baseModelId || null
});

export const mapDbToModel = (m: any): GridModel => ({
    id: String(m.id),
    name: m.name,
    columns: m.columns,
    rows: m.rows,
    marginT: m.margin_t,
    marginB: m.margin_b,
    marginL: m.margin_l,
    marginR: m.margin_r,
    gapH: m.gap_h,
    gapV: m.gap_v,
    paperSize: m.paper_size,
    paperWidth: m.paper_width,
    paperHeight: m.paper_height,
    category: m.category,
    icon: m.icon,
    type: m.type || 'rect',
    nameFontSize: m.name_font_size,
    nameColor: m.name_color,
    nameBold: m.name_bold,
    nameAlign: m.name_align,
    nameVAlign: m.name_valign,
    priceFontSize: m.price_font_size,
    priceColor: m.price_color,
    priceBold: m.price_bold,
    priceAlign: m.price_align,
    priceVAlign: m.price_valign,
    priceFontSizeTens: m.price_font_size_tens,
    priceFontSizeHundreds: m.price_font_size_hundreds,
    priceFontSizeThousands: m.price_font_size_thousands,
    priceFontSizeTenThousands: m.price_font_size_ten_thousands,
    namePosX: m.name_pos_x,
    namePosY: m.name_pos_y,
    nameWidth: m.name_width,
    nameHeight: m.name_height,
    pricePosX: m.price_pos_x,
    pricePosY: m.price_pos_y,
    priceWidth: m.price_width,
    priceHeight: m.price_height,
    barcodePosX: m.barcode_pos_x,
    barcodePosY: m.barcode_pos_y,
    promoPriceFontSize: m.promo_price_font_size,
    promoPriceColor: m.promo_price_color,
    promoPriceBold: m.promo_price_bold,
    promoPriceAlign: m.promo_price_align,
    promoPriceVAlign: m.promo_price_valign,
    promoPosX: m.promo_pos_x,
    promoPosY: m.promo_pos_y,
    promoWidth: m.promo_width,
    promoHeight: m.promo_height,
    oldPriceFontSize: m.old_price_font_size,
    oldPriceColor: m.old_price_color,
    oldPriceBold: m.old_price_bold,
    oldPriceAlign: m.old_price_align,
    oldPriceVAlign: m.old_price_valign,
    oldPricePosX: m.old_price_pos_x,
    oldPricePosY: m.old_price_pos_y,
    oldPriceWidth: m.old_price_width,
    oldPriceHeight: m.old_price_height,
    promoNameFontSize: m.promo_name_font_size,
    promoNameColor: m.promo_name_color,
    promoNameBold: m.promo_name_bold,
    promoNameAlign: m.promo_name_align,
    promoNameVAlign: m.promo_name_valign,
    promoNamePosX: m.promo_name_pos_x,
    promoNamePosY: m.promo_name_pos_y,
    promoNameWidth: m.promo_name_width,
    promoNameHeight: m.promo_name_height,
    promoNameBgColor: m.promo_name_bg_color,
    promoBarcodePosX: m.promo_barcode_pos_x,
    promoBarcodePosY: m.promo_barcode_pos_y,
    priceFormat: m.price_format,
    priceSymbolFontSize: m.price_symbol_font_size,
    priceSymbolColor: m.price_symbol_color,
    priceSymbolBold: m.price_symbol_bold,
    priceSymbolPosX: m.price_symbol_pos_x,
    priceSymbolPosY: m.price_symbol_pos_y,
    priceDecimalsFontSize: m.price_decimals_font_size,
    priceDecimalsColor: m.price_decimals_color,
    priceDecimalsBold: m.price_decimals_bold,
    priceDecimalsPosX: m.price_decimals_pos_x,
    priceDecimalsPosY: m.price_decimals_pos_y,
    promoPriceSymbolFontSize: m.promo_price_symbol_font_size,
    promoPriceSymbolColor: m.promo_price_symbol_color,
    promoPriceSymbolBold: m.promo_price_symbol_bold,
    promoPriceSymbolPosX: m.promo_price_symbol_pos_x,
    promoPriceSymbolPosY: m.promo_price_symbol_pos_y,
    promoPriceDecimalsFontSize: m.promo_price_decimals_font_size,
    promoPriceDecimalsColor: m.promo_price_decimals_color,
    promoPriceDecimalsBold: m.promo_price_decimals_bold,
    promoPriceDecimalsPosX: m.promo_price_decimals_pos_x,
    promoPriceDecimalsPosY: m.promo_price_decimals_pos_y,
    promoFontSize: m.promo_font_size,
    promoColor: m.promo_color,
    promoBold: m.promo_bold,
    promoAlign: m.promo_align,
    promoVAlign: m.promo_valign,
    bg_color: m.bg_color,
    nameBgColor: m.name_bg_color,
    priceBgColor: m.price_bg_color,
    promoBgColor: m.promo_bg_color,
    extraFields: m.extra_fields || [],
    extraFieldsPromo: m.extra_fields_promo || [],
    fontFamily: m.font_family,
    imageFit: m.image_fit || 'contain',
    imageScale: m.safety_margin || 1,
    previewImage: m.preview_image || null,
    baseModelId: m.base_model_id || null
});
