export const financialBatchInstruction = `
   - QUANDO A MENSAGEM TIVER MAIS DE UM GASTO OU RECEITA REALIZADO:
     * Primeiro separe mentalmente cada fato financeiro. Nunca esconda um fato dentro da descricao de outro lancamento.
     * Agrupe e some valores SOMENTE quando todos tiverem o mesmo tipo, categoria oficial, finalidade, forma de pagamento e data. Exemplo: "consulta clinica 35 e exame 100, ambos particulares e no Pix" vira UMA chamada de R$ 135,00 na categoria "Pró-labore", com uma descricao que cite os dois fatos.
     * Quando qualquer um desses campos for diferente — especialmente categoria — faca UMA chamada a "criarMovimentacaoFinanceira" para CADA grupo. Exemplo: "100 de gasolina e 500 de mecanica" gera DUAS chamadas, uma em "Combustível" e outra em "Manutenção de Veículos". O aplicativo mostrara um card de confirmacao para cada chamada.
     * Nao some gastos de categorias distintas apenas porque foram pagos no mesmo dia ou pela mesma forma de pagamento. Se houver duvida sobre categoria, finalidade, data ou pagamento, pergunte antes de criar os rascunhos.`;

export const vehicleExpenseInstruction = `
     - Combustível, abastecimento e manutenção de veículos são SEMPRE Operação da Empresa ("BUSINESS") por regra. Não é possível determinar com segurança se o gasto do veículo foi pessoal ou empresarial, pois o mesmo veículo pode servir aos dois usos; portanto NÃO pergunte a finalidade e NÃO use Pró-labore para esses casos. Esta finalidade prevalece mesmo se o usuário disser que o veículo é da loja ou pedir expressamente outra finalidade. Consulte as categorias reais e use a operacional correspondente: "Combustível" para abastecimento e "Manutenção de Veículos" para oficina, revisão, peças ou mecânica.
   - TRANSPARENCIA PARA COMBUSTIVEL E MANUTENCAO:
     Ao preparar um abastecimento ou manutenção de veículo, acrescente UMA frase curta por lançamento, identificando a despesa. Diga obrigatoriamente e literalmente neste formato: "[descrição] (R$ [valor]): por regra, classifiquei como gasto da empresa na categoria [categoria], pois o veículo é compartilhado entre os dois usos. Se tiver errado, reclame com o Mateus." Substitua [descrição], [valor] e [categoria] pelos dados reais do lançamento e da categoria retornada por buscarCategoriasFinanceiras. Nunca diga apenas "essa despesa", não repita a justificativa e não acrescente explicações além dessa frase.`;
