import { MarketingTemplate } from '../types';
export const LEGACY_TEMPLATES: MarketingTemplate[] = [
  {
    id: 'tpl-feed-4-5-queima',
    name: 'Queima dos Salvados (Feed 4:5)',
    aspectRatio: '4:5',
    targetWidth: 1080,
    targetHeight: 1350,
    campaignId: 'camp-queima-salvados',
    backgroundColor: '#ffffff',
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    layers: [
      {
        id: 'layer-product-image',
        type: 'PRODUCT_MAIN_IMAGE',
        name: 'Foto Ambientada do Produto',
        x: 0.05,
        y: 0.12,
        width: 0.90,
        height: 0.52,
        rotation: 0,
        zIndex: 1,
        opacity: 1,
        locked: false,
        visible: true
      },
      {
        id: 'layer-badge-queima',
        type: 'ASSET',
        assetId: 'asset-queima-salvados-badge',
        assetUrl: '/assets/queima-salvados-original.png',
        name: 'Selo Queima dos Salvados',
        x: 0.62,
        y: 0.03,
        width: 0.35,
        height: 0.28,
        rotation: -4,
        zIndex: 10,
        opacity: 1,
        locked: false,
        visible: true
      },
      {
        id: 'layer-title',
        type: 'DYNAMIC_TEXT',
        name: 'Título do Produto',
        textBinding: '{{product.name}}',
        x: 0.05,
        y: 0.67,
        width: 0.90,
        rotation: 0,
        zIndex: 5,
        opacity: 1,
        locked: false,
        visible: true,
        fontFamily: 'Montserrat, Roboto, sans-serif',
        fontSizeRelative: 0.034,
        color: '#111827',
        fontWeight: 'bold',
        textAlign: 'left'
      },
      {
        id: 'layer-price-por',
        type: 'DYNAMIC_PRICE',
        name: 'Preço Por',
        textBinding: '{{product.price}}',
        x: 0.52,
        y: 0.74,
        width: 0.43,
        rotation: 0,
        zIndex: 8,
        opacity: 1,
        locked: false,
        visible: true,
        fontFamily: 'Montserrat, sans-serif',
        fontSizeRelative: 0.055,
        color: '#dc2626',
        fontWeight: '900',
        textAlign: 'right'
      },
      {
        id: 'layer-installment',
        type: 'DYNAMIC_INSTALLMENT',
        name: 'Parcelamento',
        textBinding: '{{product.installmentValue}}',
        x: 0.52,
        y: 0.83,
        width: 0.43,
        rotation: 0,
        zIndex: 8,
        opacity: 1,
        locked: false,
        visible: true,
        fontFamily: 'Roboto, sans-serif',
        fontSizeRelative: 0.024,
        color: '#173f7a',
        fontWeight: 'bold',
        textAlign: 'right'
      },
      {
        id: 'layer-variation-gallery',
        type: 'VARIATION_GALLERY',
        name: 'Galeria de Outras Variações',
        x: 0.05,
        y: 0.74,
        width: 0.42,
        height: 0.16,
        rotation: 0,
        zIndex: 6,
        opacity: 1,
        locked: false,
        visible: true,
        direction: 'horizontal',
        thumbnailSizeRelative: 0.12,
        gapRelative: 0.02,
        borderRadius: 8,
        borderWidth: 3,
        borderColor: '#ffffff'
      }
    ]
  }
];
